--- #YAML:1.0
name:               Test-AnyEvent-Time
version:            0.01
abstract:           Time-related tests for asynchronous routines using AnyEvent
author:
    - Toshio Ito <debug.ito@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    AnyEvent:       7.01
    Scalar::Util:   0
    Test::Builder:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
